name: transfer_rl

channels:
  - pytorch
  - defaults
dependencies:
  - python=3.6
  - numpy=1.18.1
  - pip=20.0.2=py36_1
  - pytorch=1.4.0=py3.6_cuda10.1.243_cudnn7.6.3_0
  - pip:
    - box2d-py==2.3.8
    - gym==0.15.4
